package com.ezansi.app.core.data.encryption

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Log
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM encryption for learner profile data using Android Keystore.
 *
 * All learner data (profiles, preferences, chat history fields) is encrypted
 * at rest using hardware-backed keys when available. The key never leaves
 * the Keystore and cannot be exported.
 *
 * Encrypted format: `[12-byte IV][ciphertext + 16-byte GCM auth tag]`
 *
 * Security properties:
 * - 256-bit AES key generated inside hardware-backed Keystore
 * - 12-byte random IV per encryption (never reused — generated by the Cipher)
 * - 128-bit GCM authentication tag for tamper detection
 * - No padding (GCM is a streaming mode)
 *
 * @see <a href="../../docs/product/prd-v1.md">PRD §10 SP-05</a>
 */
class ProfileEncryption {

    companion object {
        /** Keystore alias for the profile encryption key. */
        private const val KEY_ALIAS = "ezansi_profile_key"
        private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"

        /** GCM initialisation vector size in bytes. */
        private const val IV_SIZE_BYTES = 12

        /** GCM authentication tag length in bits. */
        private const val AUTH_TAG_BITS = 128

        /** AES key size in bits. */
        private const val KEY_SIZE_BITS = 256

        private const val TAG = "ProfileEncryption"
    }

    private val keyStore: KeyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply {
        load(null)
    }

    /**
     * Encrypts [data] with AES-256-GCM.
     *
     * @param data Plaintext bytes to encrypt.
     * @return IV prepended to ciphertext: `[12-byte IV][ciphertext + auth tag]`.
     */
    fun encrypt(data: ByteArray): ByteArray {
        val key = getOrCreateKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv // Auto-generated 12-byte IV
        val ciphertext = cipher.doFinal(data)
        return iv + ciphertext
    }

    /**
     * Decrypts [data] that was encrypted with [encrypt].
     *
     * @param data IV-prepended ciphertext: `[12-byte IV][ciphertext + auth tag]`.
     * @return Decrypted plaintext bytes.
     * @throws javax.crypto.AEADBadTagException if the data was tampered with.
     * @throws IllegalArgumentException if the data is too short to contain an IV.
     */
    fun decrypt(data: ByteArray): ByteArray {
        require(data.size > IV_SIZE_BYTES) { "Encrypted data too short" }
        val key = getOrCreateKey()
        val iv = data.copyOfRange(0, IV_SIZE_BYTES)
        val ciphertext = data.copyOfRange(IV_SIZE_BYTES, data.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(AUTH_TAG_BITS, iv))
        return cipher.doFinal(ciphertext)
    }

    /**
     * Retrieves the existing key from the Keystore, or generates a new one
     * if this is the first time encryption is used on this device.
     */
    private fun getOrCreateKey(): SecretKey {
        keyStore.getEntry(KEY_ALIAS, null)?.let { entry ->
            return (entry as KeyStore.SecretKeyEntry).secretKey
        }

        Log.d(TAG, "Generating new encryption key")
        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            KEYSTORE_PROVIDER,
        )
        keyGenerator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                .build(),
        )
        return keyGenerator.generateKey()
    }
}
